name: Check markdown files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use nodejs
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Lint markdowns
      uses: nosborn/github-action-markdown-cli@v1.1.1
      with:
        files: .
