name: Check markdown files

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use nodejs
      uses: actions/setup-node@v5.0.0
      with:
        node-version: '18.x'
    - name: Setup link checker
      run: npm install -g jscpd markdownlint-cli markdown-link-check@3.10.3

    - name: Check links
      run: |
        cd gita
        markdown-link-check *.md
